"""Transport abstraction.

WhatsApp and Telegram delivery are planned, so the send path must not be shaped like
email. Everything above this file deals in `Message` and `Notifier`; only
`EmailNotifier` knows what SMTP is. Adding a channel is one class, not a refactor.

`send()` returns a `Receipt`, never raises, and never reports success it did not get.
That last part is what makes delivery transactional: the caller marks a notification
sent only on `Receipt.ok`, so a transport that fails silently cannot cause a row to be
marked delivered.
"""

import os
import smtplib
import ssl
import sys
from dataclasses import dataclass, field
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import formataddr, make_msgid
from pathlib import Path

AGENT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(AGENT.parent))

from engine import config as econf  # noqa: E402


@dataclass
class Message:
    subject: str
    text: str
    html: str = ""
    kind: str = ""
    priority: int = 3                      # 1 = act today, 3 = background
    meta: dict = field(default_factory=dict)


@dataclass
class Receipt:
    ok: bool
    transport: str
    detail: str = ""
    message_id: str = ""


class Notifier:
    """The interface. A transport implements `send` and `available`."""

    name = "abstract"

    def available(self) -> tuple:
        raise NotImplementedError

    def send(self, msg: Message) -> Receipt:
        raise NotImplementedError


class EmailNotifier(Notifier):
    """Gmail over SMTP+STARTTLS, matching the pattern already in production in
    `server_backup/opt/rdp-automation/lib/notify.sh`.

    Multipart/alternative: the plain-text part is not a fallback nobody reads, it is
    what shows on a phone lock screen and in notification previews. Both parts are
    generated by the same template, so they cannot drift.
    """

    name = "email"

    def __init__(self, to: str | None = None):
        self.host = econf.get("SMTP_HOST", "smtp.gmail.com")
        self.port = int(econf.get("SMTP_PORT", "587") or 587)
        self.user = econf.get("SMTP_USER")
        self.password = econf.get("SMTP_PASSWORD")
        self.sender = econf.get("SMTP_FROM") or self.user
        self.to = to or econf.get("ALERT_TO") or "bloomsrainbow09@gmail.com"

    def available(self) -> tuple:
        missing = [k for k, v in (("SMTP_HOST", self.host), ("SMTP_USER", self.user),
                                  ("SMTP_PASSWORD", self.password)) if not v]
        if missing:
            return False, f"missing {', '.join(missing)}"
        return True, f"{self.user} -> {self.to} via {self.host}:{self.port}"

    def _build(self, msg: Message) -> MIMEMultipart:
        m = MIMEMultipart("alternative")
        m["Subject"] = msg.subject
        m["From"] = formataddr(("Market alerts", self.sender))
        m["To"] = self.to
        m["Message-ID"] = make_msgid(domain="telegram-agent.local")
        # Lets the reader's client thread or filter by category without opening anything.
        if msg.kind:
            m["X-Alert-Kind"] = msg.kind
        m["X-Alert-Priority"] = str(msg.priority)
        m.attach(MIMEText(msg.text, "plain", "utf-8"))
        if msg.html:
            m.attach(MIMEText(msg.html, "html", "utf-8"))
        return m

    def send(self, msg: Message) -> Receipt:
        ok, detail = self.available()
        if not ok:
            return Receipt(False, self.name, f"not configured: {detail}")
        mime = self._build(msg)
        try:
            s = smtplib.SMTP(self.host, self.port, timeout=45)
            try:
                s.ehlo()
                s.starttls(context=ssl.create_default_context())
                s.ehlo()
                s.login(self.user, self.password)
                refused = s.sendmail(self.sender, [self.to], mime.as_string())
            finally:
                try:
                    s.quit()
                except Exception:
                    pass
            if refused:
                return Receipt(False, self.name, f"recipient refused: {refused}")
            return Receipt(True, self.name, f"delivered to {self.to}",
                           mime["Message-ID"])
        except Exception as e:
            # Never raise. A transport failure must leave the row unsent and retryable,
            # not blow up the loop that is delivering everything else.
            return Receipt(False, self.name, f"{type(e).__name__}: {e}"[:300])


class NullNotifier(Notifier):
    """Records instead of sending. Used by the gates to exercise the whole delivery
    path — dedupe, rate limit, quiet hours, transactional marking — without mailing the
    user a test message every time a gate runs."""

    name = "null"

    def __init__(self):
        self.sent: list = []

    def available(self) -> tuple:
        return True, "records in memory, sends nothing"

    def send(self, msg: Message) -> Receipt:
        self.sent.append(msg)
        return Receipt(True, self.name, f"recorded #{len(self.sent)}")


class FailingNotifier(Notifier):
    """Always fails. Proves that a failed send leaves the row unsent and retryable
    rather than silently marked delivered."""

    name = "failing"

    def available(self) -> tuple:
        return True, "always fails, on purpose"

    def send(self, msg: Message) -> Receipt:
        return Receipt(False, self.name, "simulated transport failure")


def default() -> Notifier:
    return EmailNotifier()
